# Generated by Django 5.2.1 on 2025-06-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_email_verificado_usuario_fecha_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='gimnasios/'),
        ),
    ]
