# Generated by Django 5.2.1 on 2025-06-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='calificacion',
            new_name='estrellas',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='comentario',
        ),
    ]
