# Generated by Django 5.2.1 on 2025-06-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_calificacion_reseña_estrellas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='cantidad_resenas',
            field=models.IntegerField(default=0),
        ),
    ]
