# Generated by Django 5.2.3 on 2025-06-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gimnasio_cantidad_resenas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='texto',
            field=models.TextField(blank=True, help_text='Reseña opcional (máximo 500 caracteres)', max_length=500, null=True),
        ),
    ]
