# Generated by Django 5.2.3 on 2025-06-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reseña_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reseña',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reseña',
            unique_together={('usuario', 'gimnasio')},
        ),
    ]
