# Generated by Django 5.2.3 on 2025-06-22 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reseña_editado_reseña_fecha_edicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
